### PR TITLE
feat: use lambda layer and newrelic lambda handler wrapper

### PR DESCRIPTION
**Pull request by mohamed-cds**
Setup environment variables required for the lambda api to successfully integrate with newrelic

related:

- cds-snc/notification-api/pull/1507

### CODE REVIEW

**Review by jimleroyer — APPROVED** [review]
Let's try this out!

**Comment by mohamed-cds** [comment]
Need to make changes to notification-api before this moves forward. Putting this back to draft until then

**Review by jimleroyer — CHANGES_REQUESTED** [review]
Alright I'll remove my review and fictive request some changes until it's ready.

**Review by sastels — APPROVED** [review]
:shipit:

**Pull request merged**
