### PR TITLE
feat: specify SSL policy for ALB

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Pick an appropriate SSL policy for the load balancer, according to:

- recommendations: https://canada-ca.github.io/cloud-guardrails/EN/07_Protect-Data-in-Transit.html
- what other teams do: https://github.com/cds-snc/covid-alert-server-staging-terraform/blob/6232ad547cba9d4dd57300ea4377b2e3821442e7/server/aws/lb.tf#L82

See https://aws.amazon.com/about-aws/whats-new/2019/10/application-load-balancer-and-network-load-balancer-add-new-security-policies-for-forward-secrecy-with-more-strigent-protocols-and-ciphers/

### CODE REVIEW

**Review by QuanNguyen-CDS — COMMENTED** [review]
Is there a reason why we are not using `ELBSecurityPolicy-FS-1-2-Res-2020-10` ? which is the latest

**Comment by AntoineAugusti** [comment]
@QuanNguyen-CDS Not sure if we can pick the latest. Looking again at the table, the latest only allows 4 ciphers. 2019-08 allows a bit more ciphers. The only recommendation we have, to my knowledge, is that we should only accept TLSv1.2.

Took at look at https://cyber.gc.ca/en/guidance/guidance-securely-configuring-network-protocols-itsp40062, section "Table 3: Recommended Cipher Suites for TLS 1.2" and the recommended ciphers match the 2019-08 policy.

**Review by QuanNguyen-CDS — APPROVED** [review]
LGTM based upon documentation

**Comment by AntoineAugusti** [comment]
cc @maxneuvians, we talked about that yesterday

**Comment by AntoineAugusti** [comment]
All good in staging
Screen Shot 2021-04-20 at 08 33 56

**Pull request merged**
