### PR TITLE
increase dev sns spend limit

### PR DESCRIPTION
**Pull request by sastels**
# Summary | Résumé

increase this to allow for testing.

## Related Issues | Cartes liées

* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/396

## Before merging this PR

Read code suggestions left by the
[cds-ai-codereviewer](https://github.com/cds-snc/cds-ai-codereviewer/) bot. Address
valid suggestions and shortly write down reasons to not address others. To help
with the classification of the comments, please use these reactions on each of the
comments made by the AI review:

| Classification      | Reaction | Emoticon |
|---------------------|----------|----------|
| Useful              | +1       | 👍        |
| Noisy               | eyes     | 👀        |
| Hallucination       | confused | 😕        |
| Wrong but teachable | rocket   | 🚀        |
| Wrong and incorrect | -1       | 👎        |

The classifications will be extracted and summarized into an analysis of how helpful
or not the AI code review really is.

## Test instructions | Instructions pour tester la modification

None

## Release Instructions | Instructions pour le déploiement

None.

## Reviewer checklist | Liste de vérification du réviseur

* [ ] This PR does not break existing functionality.
* [ ] This PR does not violate GCNotify's privacy policies.
* [ ] This PR does not raise new security concerns. Refer to our GC Notify Risk Register document on our Google drive.
* [ ] This PR does not significantly alter performance.
* [ ] Additional required documentation resulting of these changes is covered (such as the README, setup instructions, a related ADR or the technical documentation).

> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.

### CODE REVIEW

**Review by ben851 — COMMENTED** [review]
I think we tried 100 and it threw an error saying we weren't clear for that much $$ 

I'd ask you to verify that it works first but dev is in between deployments right now - give me a bit and we can try later

**Comment by sastels** [comment]
I set it manually in the [console](https://ca-central-1.console.aws.amazon.com/sns/v3/home?region=ca-central-1#/mobile/text-messaging) here when doing testing, its all good.

**Comment by sastels** [comment]
ah, we've moved the variables out of the hcl fields, so I should go track down `sns_monthly_spend_limit` and see if I can change this PR to set it...

**Comment by sastels** [comment]
... and it's set to 100 in 1Password. So my work here is done.

**Pull request closed without merging**
