### PR TITLE
fix: remove CloudWatch WAF ACL log destination

### PR DESCRIPTION
**Pull request by patheard**
# Summary
Delete the CloudWatch WAF ACL logging destination as the S3
bucket + Firehose is required by Cloud Based Sensor. An Athena
query has been added to create a table from the WAF logs.

Also fixes the Athena query that create's a table from the load balancer
S3 access logs bucket. The previous query was running successfully, 
but failing to pull any data into the new table.

### CODE REVIEW

**Review by sastels — APPROVED** [review]
LGTM. 
We don't have any metrics or alerts based on those log groups?

**Comment by patheard** [comment]
> LGTM. We don't have any metrics or alerts based on those log groups?

No, we added it a while back since we didn't have an WAF ACL logging configured and wanted to test out using CloudWatch, which had just recently been added as an option.

**Comment by jimleroyer** [comment]
So we removed cloudwatch because it's either the s3 bucket+firehose or cloudwatch? This is handy to have logs in cloudwatch.

**Comment by patheard** [comment]
Yeah, sadly a WAF ACL can only support one logging destination 😢 

To try and make up for it, I added a new saved query that can create an Athena table from the WAF logs in the S3 bucket.

**Pull request merged**
