### PR TITLE
Added a non-wildcard version of the API SAN

### PR DESCRIPTION
**Pull request by jimleroyer**
# Summary | Résumé

Trying out a non-wildcard of the API SAN in addition to a wildcard version. This is to help out the SSC users that are using WebLogic, which can't accept wildcard for the SANs.

# Test instructions | Instructions pour tester la modification

Look out for the non-wildcard API entry in the certificate subject alternative names when deployed.

### CODE REVIEW

**Review by andrewleith — APPROVED** [review]
LGTM - should be functionally equivalent, and will hopefully solve the downstream client's issue with their webserver.

**Comment by mohamed-cds** [comment]
Looks like tfsec might need to be bumped. We're on `v0.39.26` while the latest is `v1.26.3`. Since we're behind this significantly this is a good opportunity to switch to checkov which is the one we've been standardizing around for terraform security scans.

cc/ @sastels since i think you looked into this in the past

**Comment by jimleroyer** [comment]
@mohamed-cds Is that a low effort upgrade? just pushing the new version?

**Comment by mohamed-cds** [comment]
@jimleroyer high chance it'll flag a-lot of items if you jump to a newer version in this PR. It'd recommend it as a standalone activity since you'll have to update TF resources or ignore items that we don't agree with.

I'd also switch to the official Github action instead of the one you current have. This can be done in this PR without any negative actions (famous last words).

triat/terraform-security-scan@v2.2.1 -> aquasecurity/tfsec-action@v1.0.0

**Review by mohamed-cds — APPROVED** [review]
Let's give this a try 🚀 ✅

**Pull request merged**
