### PR TITLE
feat: bumping version, adding prod definitions for alarms and s3 policy

### PR DESCRIPTION
**Pull request by QuanNguyen-CDS**
Release #222 , #223, #224 to production. 
PRs are related S3 policy update (to not be public) and lifecycle rules for `/tmp`

### CODE REVIEW

**Review by AntoineAugusti — CHANGES_REQUESTED** [review]
You'll need to split it in 2 in production as well. Only release up to https://github.com/cds-snc/notification-terraform/pull/221 (0.82.0 I think) to create the new output in production and then up to 0.84.0

**Comment by QuanNguyen-CDS** [comment]
> You'll need to split it in 2 in production as well. Only release up to #221 (0.82.0 I think) to create the new output in production and then up to 0.84.0

Thanks @AntoineAugusti for the heads up and catching this.

**Comment by AntoineAugusti** [comment]
This PR was split in two, the first part was released in https://github.com/cds-snc/notification-terraform/pull/226

**Review by AntoineAugusti — APPROVED** [review]
LGTM, wait a few hours before merging this one

**Pull request merged**
