### PR TITLE
Secondary target group

### PR DESCRIPTION
**Pull request by ben851**
# Summary | Résumé

This is the first PR to support fixing the EKS load balancer services without downtime as documented here:
https://github.com/cds-snc/notification-manifests/pull/1947

# Test instructions | Instructions pour tester la modification

- Terraform apply should add new target groups
- Verify that all hosted URLs on EKS still work as expected:
   - https://staging.notification.cdssandbox.xyz
   - https://api-k8s.staging.notification.cdssandbox.xyz
   - https://documentation.staging.notification.cdssandbox.xyz
   - https://api.document.staging.notification.cdssandbox.xyz/_status

### CODE REVIEW

**Comment by sastels** [comment]
Would this PR need to be released to prod before we can do the next steps?

**Comment by ben851** [comment]
> Would this PR need to be released to prod before we can do the next steps?
Yup! The good news is that none of these steps are time sensitive.

**Review by sastels — APPROVED** [review]
LGTM - when should we merge to staging / release to prod?

**Comment by ben851** [comment]
> LGTM - when should we merge to staging / release to prod?

We can merge to staging and validate overnight that it doesn't break anything

**Pull request merged**
